BTLNHOM01/Models/KhachHang.cs
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using System.Linq;
using System.Web;
using BTLNHOM01.Models;
namespace BTLNHOM01.Models
{
    [Table("KhachHangs")]
    public class KhachHang
    {
        [Key]
        public string MaKH { get; set; }
        public string TenKH { get; set; }
        [AllowHtml]
        public string DiachiKH { get; set; }
        [DataType(DataType.PhoneNumber)]
        [Display(Name = "Phone Number")]
        [Required(ErrorMessage = "Phone Number Required!")]
        [RegularExpression(@"^\(?([0-9]{3})\)?[-. ]?([0-9]{3})[-. ]?([0-9]{4})$",
                      ErrorMessage = "Entered phone format is not valid.")]
        public string SoDT { get; set; }
    }

    internal class AllowHtmlAttribute : Attribute
    {
    }
}

BTLNHOM01/Controllers/KhachHangController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using BTLNHOM01.Data;
using BTLNHOM01.Models;
using X.PagedList;


namespace BTLNHOM01.Controllers
{
    public class KhachHangController : Controller
    {
        private readonly ApplicationDbcontext _context;

        public KhachHangController(ApplicationDbcontext context)
        {
            _context = context;
        }

        // GET: KhachHang-Phan trang
        public async Task<IActionResult> Index(int? page, int? PageSize)
        {
            ViewBag.PageSize = new List<SelectListItem>()
                {
                    new SelectListItem() { Value="3", Text="3"},
                    new SelectListItem() { Value="5", Text="5"},
                    new SelectListItem() { Value="10", Text="10"},
                    new SelectListItem() { Value="15", Text="15"},
                    new SelectListItem() { Value="25", Text="25"},

                };
                int pagesize = (PageSize ?? 3);
                ViewBag.psize = PageSize;
                var model = _context.KhachHang.ToList().ToPagedList(page ?? 1, pagesize);
                return View(model);
                         
        }
        // GET: KhachHang/Details/5
        public async Task<IActionResult> Details(string id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var khachHang = await _context.KhachHang
                .FirstOrDefaultAsync(m => m.MaKH == id);
            if (khachHang == null)
            {
                return NotFound();
            }

            return View(khachHang);
        }

        // GET: KhachHang/Create
        public IActionResult Create()
        {
            return View();
        }

        // POST: KhachHang/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("MaKH,TenKH,DiachiKH,SoDT")] KhachHang khachHang)
        {
            if (ModelState.IsValid)
            {
                _context.Add(khachHang);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            return View(khachHang);
        }

        // GET: KhachHang/Edit/5
        public async Task<IActionResult> Edit(string id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var khachHang = await _context.KhachHang.FindAsync(id);
            if (khachHang == null)
            {
                return NotFound();
            }
            return View(khachHang);
        }

        // POST: KhachHang/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(string id, [Bind("MaKH,TenKH,DiachiKH,SoDT")] KhachHang khachHang)
        {
            if (id != khachHang.MaKH)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(khachHang);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!KhachHangExists(khachHang.MaKH))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            return View(khachHang);
        }

        // GET: KhachHang/Delete/5
        public async Task<IActionResult> Delete(string id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var khachHang = await _context.KhachHang
                .FirstOrDefaultAsync(m => m.MaKH == id);
            if (khachHang == null)
            {
                return NotFound();
            }

            return View(khachHang);
        }

        // POST: KhachHang/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(string id)
        {
            var khachHang = await _context.KhachHang.FindAsync(id);
            if (khachHang != null)
            {
                _context.KhachHang.Remove(khachHang);
            }

            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool KhachHangExists(string id)
        {
            return _context.KhachHang.Any(e => e.MaKH == id);
        }
    }
}

BTLNHOM01/Views/KhachHang/Create.cshtml
@model BTLNHOM01.Models.KhachHang

@{
    ViewData["Title"] = "Create";
}

<h1>Create</h1>

<h4>KhachHang</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Create">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="MaKH" class="control-label"></label>
                <input asp-for="MaKH" class="form-control" />
                <span asp-validation-for="MaKH" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="TenKH" class="control-label"></label>
                <input asp-for="TenKH" class="form-control" />
                <span asp-validation-for="TenKH" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="DiachiKH" class="control-label"></label>
                <input asp-for="DiachiKH" class="form-control" />
                <span asp-validation-for="DiachiKH" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="SoDT" class="control-label"></label>
                <input asp-for="SoDT" class="form-control" />
                <span asp-validation-for="SoDT" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Create"  />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

BTLNHOM01/Views/KhachHang/Delete.cshtml
@model BTLNHOM01.Models.KhachHang

@{
    ViewData["Title"] = "Delete";
}

<h1>Delete</h1>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>KhachHang</h4>
    <hr />
    <dl class="row">
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.TenKH)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.TenKH)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.DiachiKH)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.DiachiKH)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.SoDT)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.SoDT)
        </dd>
    </dl>
    
    <form asp-action="Delete">
        <input type="hidden" asp-for="MaKH" />
        <input type="submit" value="Delete" class="btn btn-danger" /> |
        <a asp-action="Index">Back to List</a>
    </form>
</div>

BTLNHOM01/Views/KhachHang/Details.cshtml
@model BTLNHOM01.Models.KhachHang

@{
    ViewData["Title"] = "Details";
}

<h1>Details</h1>

<div>
    <h4>KhachHang</h4>
    <hr />
    <dl class="row">
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.TenKH)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.TenKH)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.DiachiKH)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.DiachiKH)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.SoDT)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.SoDT)
        </dd>
    </dl>
</div>
<div>
    <a asp-action="Edit" asp-route-id="@Model?.MaKH">Edit</a> |
    <a asp-action="Index">Back to List</a>
</div>

BTLNHOM01/Views/KhachHang/Edit.cshtml
@model BTLNHOM01.Models.KhachHang

@{
    ViewData["Title"] = "Edit";
}

<h1>Edit</h1>

<h4>KhachHang</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Edit">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <input type="hidden" asp-for="MaKH" />
            <div class="form-group">
                <label asp-for="TenKH" class="control-label"></label>
                <input asp-for="TenKH" class="form-control" />
                <span asp-validation-for="TenKH" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="DiachiKH" class="control-label"></label>
                <input asp-for="DiachiKH" class="form-control" />
                <span asp-validation-for="DiachiKH" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="SoDT" class="control-label"></label>
                <input asp-for="SoDT" class="form-control" />
                <span asp-validation-for="SoDT" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Save" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

BTLNHOM01/Views/KhachHang/Index.cshtml
@model IEnumerable<BTLNHOM01.Models.KhachHang>


@{
    ViewData["Title"] = "Index";
}

<h2 class="w3-center w3-text" style=" font-family: Times New Roman; font-size:50px ">Khách hàng</h2>

<p>
    <a asp-action="Create">Thêm khách hàng mới </a>
</p>
<form asp-controller="KhachHang" asp-action="Index">
    <p>
        Tìm kiếm: <input type="text" name="SearchString" />
        <input type="submit" value="Lọc"/> 
    </p>
</form> 
<style>
#customers {
  font-family: Arial, Helvetica, sans-serif;
  border-collapse: collapse;
  width: 100%;
}

#customers td, #customers th {
  border: 1px solid #ddd;
  padding: 8px;
}

#customers tr:nth-child(even){background-color: #f2f2f2;}

#customers tr:hover {background-color: #ddd;}

#customers th {
  padding-top: 12px;
  padding-bottom: 12px;
  text-align: left;
  background-color: #04AA6D;
  color: white;
}
</style>
<table id="customers">
  <tr>
    <th> Mã khách hàng  </th>
    <th> Tên khách hàng  </th>
    <th> Địa chỉ </th>
    <th> Số điện thoại </th>
    <th> Action </th>
  </tr> 
@foreach (var item in Model) {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.MaKH)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.TenKH)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.DiachiKH)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.SoDT)
            </td>
            <td>
                <a asp-action="Edit" asp-route-id="@item.MaKH">Edit</a> |
                <a asp-action="Details" asp-route-id="@item.MaKH">Details</a> |
                <a asp-action="Delete" asp-route-id="@item.MaKH">Delete</a>
            </td>
        </tr>
}
    </tbody>
</table>